### ISSUE TITLE
Default admin password

### ISSUE THREAD

**Issue by officeabg** [linagora/openpaas-esn#10]
Hi!
I saw that in config/users.json is a default admin with admin@linagora.com but what is the password?
I am on a clean install.
The register form on the login page doesn't work!

**Comment by chamerling** [comment]
hi @officeabg 

You should try 'secret' as password. I am not sure that user schema is up to date so I will recommend to use docker if you want to test OpenPaaS. The documentation available at https://github.com/linagora/openpaas-esn/tree/master/docker/doc and especially https://github.com/linagora/openpaas-esn/blob/master/docker/doc/run.md

**Comment by chamerling** [comment]
OK so I just tested and the file auth does not work as is. BTW, if you use docker, you will have all the components started so that you can use all the features of the platform

**Comment by officeabg** [comment]
Tried "secret" and does not work. 
This is sad as I was looking forward to deep test open-paas.
I will try docker.
Thanks!

**Comment by chamerling** [comment]
Hi @officeabg,

Any news? Did you succeed on using OpenPaaS. FYI, I just published an article about docker which you can use to configure and provision OpenPaaS http://linagora.github.io/openpaas-tip-of-the-day/docker-compose-dev/

**Comment by officeabg** [comment]
Hi! 
I did installed it with docker. This was a pain as I don't use docker. I realy hate the way you packed everything. Maybe makes sense from your development stand point. Not everything worked ( mail, elasticsearch, register button). Probably didn't do something the way I supposed to. 
This is tooo bad. I really liked everything about the conccept but not the way the code lies.
I really need something very close for my next project and thought this is a good fit.
Please understand my 2 cents. I would NEVER and I underline NEVER use docker for a production product. I know it is a hype for now, but this is just something to get things done quickly not a thing to pursute for a stable production enviroment.
Maybe for a future project I will follow this project, but for now I just have to take a pass. 
Please understand that I am really sad about this. Openpaas was the closest thing for what I need at this moment. Maybe if you would listen to @macbook on 21 Jul 2015 this project would had more traction.

**Comment by chamerling** [comment]
Hi @officeabg,

I am a bit disappointed about your message. We never discussed about a production environment and I never said that you must use docker for production. You asked for help to setup the platform and I told you that you should try docker to do so because it really ease the platform setup. OpenPaaS is a huge platform, not a tiny project so you have to understand that all can not work out of the box like without a little effort.

"I really liked everything about the conccept but not the way the code lies": Once again, this is not a simple node application. The project is composed of tons of modules, with dependencies. We can plug modules, customize the platform, etc etc. So what is the problem with that?

**Comment by officeabg** [comment]
Hi @chamerling !
I read my message again and sounded to harsh instead of the actual message I wanted to get to you.
I still like very much the project. I understand the complexity and the work you guys put on it. I am really dissapointed that I cant afford from the time perspective to be engaged for now with the project I have to do (deadline and such).

**Comment by ddolcimascolo** [comment]
Hi @officeabg,

As you may know, we are actively developing the software, and things are evolving quickly. For instance two weeks ago we were still tied to an old version of elastic, because we were using a deprecated technology (rivers). This has been fixed! 
We are continuously trying to improve the product, and installation / deployment is a major concern for us.. 

I suggest we ping you back when we have made some progress on this topic, so that you can give OpenPaas another try. How does that sound? 

Regards, 
David

**Comment by officeabg** [comment]
Hi! Please do! I like very much the social engadgement of your app. Also has some top noch features that I find them important (like email, elastic, search, groups, and community features). 
If you would like some pointers I would do some kind of blogging platform to add to openpaas so users can post diferent kind of stuff like tutorials, exlanation articles, categorized articles and so on ...

**Comment by tanandy** [comment]
yes you are right, we plan to make things simpler and update doc https://docs.open-paas.org/

stay tune
