### ISSUE TITLE
Simplify collaboration

### ISSUE THREAD

**Issue by maxbook** [linagora/openpaas-esn#2]
The deployment of the application is currently too complex to attract more contributors, we should simplify the procedure and improve the documentation.
Would it be possible to approach the application NodeJS structuring standarts?
Why not set up a Heroku deployment?
Create Grunt script to simplify the deployment of mongodb database?

**Comment by chamerling** [comment]
This is a task we are currently working on.

- What do you mean by 'approach the application NodeJS structuring standarts'? FYI we created a component-based framework which is really powerful and allows to create and manage large nodejs applications.
- We depend on so much services to deploy on heroku for now: mongo, redis, mailserver, dav server, etc...

We plan to provide more docker-basd stuff so that users and developers can start to play with it.

Cheers,

**Comment by maxbook** [comment]
Je suis désolé je prend trop de temps à m'exprimer en anglais.

Ce que je voulais dire, c'est que j'ai voulu contribuer au projet mais c'est vrai que l'en arrivant devant le déploiement ça fait un peu peur, et c'est quand même pas mal de travail. Pour docker ça serait super bien. Enfin, voilà je trouve que le déploiement est un peu complexe à cause des bases de données, c'est dommage, changer ça pourrait attirer plus de visiteurs, voir qu'elles technos utiliser.

Et pour node je suis habitué à une structure plus 'MVC', et à retrouver le frontend dans /public et le backend dans /app, ce n'est que des détails mais beaucoup de projets l'utilisent (on croirait presque à un vrai standard ^^). Et pourquoi un un coup de coffeescript :)

Bref rien de bien méchant, si je peu aider, ça serait avec grand plaisir, pour ma par c'est beaucoup de JS (Node, Angular, etc..) mais aussi de l'UX et UI si besoin :D

**Comment by rpignolet** [comment]
If you do not care about search feature like member search or invite member into a community you can just install MongoDB and Redis. These two database are really easy to install and you will have a working ESN.

**Comment by sieira** [comment]
Regarding @maxbook comment, I agree that not having some "standard" MVC structure makes the learning curve really slow down, and may dissuade contributors.

It's not that OpenPaas should follow a [de facto standard app structure](http://www.terlici.com/2014/08/25/best-practices-express-structure.html), but since it looks like it scales really quick, I would really be nice to have some shorthand chart for the project structure, or some brief document detailing the directory tree.

Something like this:

![src_tree](https://cloud.githubusercontent.com/assets/13233859/8986221/7c8fde8a-36db-11e5-9adf-7f9bd086195b.png)

**Comment by chamerling** [comment]
We are agree that this can be hard to manage at the beginning. The structure is quite easy to understand:

- backend for backend modules
- frontend for frontend ones

Then we added the modules folder at the root of the project. The idea is to have a component-based approach which relies on the backend modules. This will really help to have more contributors since it allows to cut the whole app into independant modules with a hot loader dependencies system:

You will be able to create your own private module, plug them to openpaas, or shutdown some core ones . For example let's say that you do not care about contacts modules so you can shutdown just this one.

As a summary OpenPaaS is not a simple express application, it is a huge, customizable and extensible application.

**Comment by tanandy** [comment]
hi guys, we plan to rearchitecture and splits modules. stay tune
