### ISSUE TITLE
OpenPaaS with Linux on cloud instance

### ISSUE THREAD

**Issue by lecoqnicolas** [linagora/openpaas-esn#32]
I have tried several times the wiki page (http://docs.open-paas.org/getting-started/linux/) on a Cloudwatt instance (Debian Jessie, ports 8080 ... open), and only the nginx server is available. 

I noticed no specific error upon follwng the procedure.

It turns out I do not have a particular DNS setup, so I have to access the server via its floating IP.

**Comment by heroandtn3** [comment]
Hello, you need to add this line to both your local machine and cloud server:

`x.x.x.x openpaas.local davserver.openpaas.local james.openpaas.local`

In cloud server, `x.x.x.x` can be `127.0.0.1` while in your local machine, it should be the cloud server's IP address.

**Comment by lecoqnicolas** [comment]
I cannot edit the hosts file on my local machine, so there is the explanation.

Meanwhile, I set up another instance with docker-compose, and I have come to the point where the login page works. Launching took a lot more than a couple of minutes, but then, it is only one CPU...

What platform do you recommend for production on a cloud instance? Package or docker?

**Comment by heroandtn3** [comment]
Launching the docker compose instance the first time will take time because it has to download all the required Docker images. The next times will be faster since it's only about creating containers.

> What platform do you recommend for production on a cloud instance? Package or docker?

Should be package. Docker Compose is supposed to be used for trying purpose. Of course, if you still want to use Docker, you can give it a chance at your risk.

**Comment by lecoqnicolas** [comment]
Thanks.
