### ISSUE TITLE
Few issues with Videoconference modules

### ISSUE THREAD

**Issue by alexcustos** [linagora/openpaas-esn#53]
Hello, When I try to install Videoconference on my OpenPaaS instance, I found [the documentation](https://docs.open-paas.org/modules/videoconference/index/) is not helping in many aspects, so I believe the main OpenPaaS repository is a right place for the issue. If it's not, please let me know the correct direction.

Here the issues:
1) The modified [docker-jitsi-meet](https://ci.linagora.com/linagora/lgs/openpaas/docker-jitsi-meet) is not available (at least for public) and [linagora/jitsi-meet](https://github.com/linagora/jitsi-meet) has not enough information to build it as a Docker container.

2) [linagora.esn.videoconference.calendar](https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.videoconference.calendar) module crashes with error:
```
  message: 'Fatal error:',
  meta: TypeError: Cannot read property 'register' of undefined
  at Object.init (/var/www/modules/linagora.esn.videoconference.calendar/backend/lib/email-processors/index.js:10:36)
    at Object.deploy (/var/www/modules/linagora.esn.videoconference.calendar/index.js:48:27)
    at Promise.apply (/var/www/modules/linagora.esn.videoconference.calendar/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/var/www/modules/linagora.esn.videoconference.calendar/node_modules/q/q.js:788:41)
    at /var/www/modules/linagora.esn.videoconference.calendar/node_modules/q/q.js:1391:14
    at runSingle (/var/www/modules/linagora.esn.videoconference.calendar/node_modules/q/q.js:137:13)
    at flush (/var/www/modules/linagora.esn.videoconference.calendar/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

3) [linagora.esn.videoconference](https://ci.linagora.com/linagora/lgs/openpaas/linagora.esn.videoconference) seems not working properly neither. It registers API backend at /videoconference/api/conference/, but [openpaas-videoconference-app](https://ci.linagora.com/linagora/lgs/openpaas/openpaas-videoconference-app) failes with error message `We are sorry, but the conference room couldn't be joined...`. The app seems communicates well to offical Jitsy Meet (camera turns on, and console shows no error).

4) And there is one more issue with the linagora.esn.videoconference module, its menu item points to `/[object Object]`.

**Comment by chamerling** [comment]
Did you also added `linagora.esn.videoconference` module in `config/default.json` so that the module is loaded? If yes, as an OpenPaaS admin, you should see the videoconference module administration in the Modules section

![capture d ecran 2019-01-17 a 10 55 48](https://user-images.githubusercontent.com/264403/51310237-8a30d600-1a46-11e9-8bb6-e9d321ff343e.png)

Then you have to set 2 URLs: The `Jitsi HTTP URL` is the HTTP URL of your jitsi instance, the `Conference application URL` is the HTTP URL of where you deployed the openpaas-videoconference-app.

Once configured, you should be able to click on the videoconference app in the application menu which will open the openpaas-videoconference-app in a new browser.

On the openpaas-videoconference-app, you also have to do some configuration. You have to tell it where the OpenPaaS instance is running so it can call it. This is explained here https://ci.linagora.com/linagora/lgs/openpaas/openpaas-videoconference-app#run (even if not running in docker, sorry this is not clear and will be fixed).

Authentication at the jitsi side is in the roadmap

**Comment by alexcustos** [comment]
Yes, with authentication disabled, all seems working perfectly normal. Except, I still can't get the menu item point to the Conference app URL. But when I open window/tab manually, everything looks good. I tried to debug that part, but I only managed to replace the icon, the URL part was not changed even when I replaced it with static text. It seems that call doesn't meet the library's interface.

![screenshot_20190117_151337](https://user-images.githubusercontent.com/6049175/51319756-fa535200-1a6e-11e9-97c2-4ee6c14ab5c4.png)

**Comment by sieira** [comment]
I'm also having trouble with this

1. I cannot access https://ci.linagora.com/linagora/lgs/openpaas/docker-jitsi-meet either. I tried with my gitlab account, but I guess it is not entirely public. I managed to make it work using the original docker-jitsi-meet

2. I'm using a custom image based on linagora/esn:latest, where I installed the required modules (I will add the calendar update to it, so I can try the suggested solution)

5. If I directly use jitsi, both as Jitsi HTTP url and as conference application URL, it works. I am however unable to make the openpaas app work as well:

5.1 Frontend redirects to APP_URL/token, resulting in a 404
5.2 If I go to the APP_URL, and login there, it seems to try to access the conference list, but I end up with a security failure SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by LawlessWorld** [comment]
Is there any update to the video conference module in v 1.8?

**Comment by tanandy** [comment]
@chamerling is still video conference module supported in OP ?

**Comment by chamerling** [comment]
Hello,

Yes it is, it allows to link to a Jitsi instance in several places. Anyway the issues related to Jitsi docker images can be skipped. There is no need to use our images anymore.
