### ISSUE TITLE
Docker Development questions/issues/documentation 

### ISSUE THREAD

**Issue by fredhampton** [linagora/openpaas-esn#79]
We are attempting to install a docker developer environment on ubuntu following the documentation here:
https://github.com/linagora/openpaas-esn/blob/master/doc/develop.md

1. When we reach the step to start docker we are confused about what the ESN_HOST variable should be.
 Should it be the i.p. address of our local machine ?
Should it be the ip address of the domain name that we are testing OpenPass on (https://example.com)
2. In our openpaas-esn directory and in /docker/dockerfiles/dev/ the Docker-Compose.yml has the  DOCKER_IP variable set to  “localhost”. 
Is this the correct setting for this variable ? 
Should it be  the i.p. address of our local machine ?
Should it the ip address of the domain name that we are testing OpenPass on (https://example.com)
3. Is there any documentation on how the portal admin can configure the James server so that users can both send and receive emails within the unified inbox ?
4. Is there any documentation on how to configure the JMAP settings as the portal admin ?
5. Is there any documentation on how to configure the DAV server settings as the portal admin?

Thanks !

**Comment by alexcustos** [comment]
Here's the documentation you seem missed https://github.com/linagora/openpaas-esn/tree/master/docker/doc.

For the other questions, I would recommend to provision the instance with demo data and use those values as a template for clean deployment. At the moment, OpenPaaS doesn't have UI for many options, and the developers used their own James build. Sometimes it's hard to figure out how to apply Apache documentation to this system.

I don't expect developers or anyone else will explain those things in details before the system will be officially production-ready. It makes no sense to maintain detailed documentation at this point. You may find a lot of outdated examples (mainly in French). Because of this, no one wants you to end up with an open relay or any other insecure configuration. In other words, OpenPaaS is good if you don't mind to help with testing or developing, but it still requires some general knowledge about Docker and MTA to publish suitable and well-secured configuration on the Internet.

BTW, I would be glad to stand corrected when some developers reach this issue.

**Comment by fredhampton** [comment]
I'am using Docker compose on linux.
I have read the documentation and made some progress.
I have a few issues that I cannot find any documentation for.

When configuring the James module from the portal admin interface how can i find what the correct Web Admin API endpoint is for the Backend and Frontend ?

When configuring the Unified Inbox from the portal admin interface how can I find what the correct JMAP API, Upload API, Download API should be ?

Thanks for your help !

**Comment by tanandy** [comment]
hi thank you for your feedback, we plan to make better documentation in the future
stay tune
