### ISSUE TITLE
Licensing Question - Section 1 Notices and Attribution

### ISSUE THREAD

**Issue by teach-ed** [linagora/openpaas-esn#88]
While going through the licensing language with my attorney some questions arose that I hope can be answered here.

[**This is from section 1 - Notices and Attribution:**](https://github.com/linagora/openpaas-esn/blob/master/LICENSE)

_The interactive user interfaces in modified source and object code versions of
this program must display Appropriate Legal Notices, as required under Section
5 of the GNU Affero General Public License version 3._

_In accordance with Section 7 and subsection (b) of the GNU Affero General
Public License version 3, these Appropriate Legal Notices consist in the
display of the Signature Notice “OpenPaaS is powered by Linagora.” **for any 
and all type of outbound messages (e.g. e-mail and meeting requests). 
Retaining this Signature Notice in any and all free and Open Source versions 
of OpenPaaS is mandatory notwhistanding any other terms and conditions.**_

As it reads all versions of the software must include in the email signature or calendar invites the "_OpenPaaS is powered by Linagora._" 

The issue that was pointed to me is if our users edit the signature templates and not include this language in their outbound emails that we would be potentially in violation of the terms of this license.  

I have two questions;
1. are we misinterpreting this section of the legal language?
2. If this is a requirement, why is this language not embedded within the site and all emails generated via outbound or is this expected on us, users who build from source to embed this language ourselves?  

Thanks and sorry if this isnt the right place to bring this question up.

**Comment by teach-ed** [comment]
Sorry, but this was never answered - can someone from openpaas actually address this rather than having it sit for months on end?

**Comment by tanandy** [comment]
Hi @teach-ed thank you for your feedback. i will ask to the legal team

**Comment by GurjinderSingh** [comment]
little update in other issue of similar licence 

https://github.com/linagora/Twake/issues/584

**Comment by tanandy** [comment]
@shivam9593 @BenoitTallandier any news from the legal team ?

**Comment by shivam9593** [comment]
@tanandy No updates yet. But I will update soon.

**Comment by shivam9593** [comment]
Hello @teach-ed, First of all, I would like to apologize for replying so late to your questions. This is definitely the right place to bring these questions up and thank you for reaching out to us. I will try to answer both of your questions to the best of my abilities. 

> 1. are we misinterpreting this section of the legal language?
No, you're not misinterpreting this section of the legal language. It is mandatory to include the signature notice "OpenPaaS is powered by LINAGORA" for all the outbound messages (e-mails, calendar invites, etc.). However, you are not required to include this signature notice for all emails and messages within your company or enterprise.

> 2. If this is a requirement, why is this language not embedded within the site and all emails generated via outbound or is this expected on us, users who build from source to embed this language ourselves?
You are absolutely right and this language is not embedded within the site and all emails generated via outbound and this is a problem. We have not embedded it at this moment because we use OpenPaaS for our company e-mails or we sell this as a collaborative tool to our customers. Unfortunately, community members who want to use OpenPaaS for outbound messages and e-mails need to embed this language on their own, for now. 

Let me know if you have any questions, and I will be happy to address them much quicker.

**Comment by teach-ed** [comment]
Well that is all said and well, it's your guys software and you can choose how to distribute it, if at all.  There are two issues with your team; first, I've been on this topic and asking this question to your team for over a year - that's just unacceptable and it only came to light because twake started to see traction and i brought it to them.  Secondly, you are now falsely claiming to be opensource and should make this notice clear to your users. rather than just telling people this is the intent, it's a branded and licensed system and they can be sued by Linagora, at any time, for any reason.  That's just some half assed legal language that is an amendment to the original OS License.  This gives you some BS claim to be open source when you are not.

We stopped using your system long ago ;) and I'll be sure to to let people know that about your garbage legal language.  Linagora is giving themselves power over their users and doing it in a shady way; this is the opposite of being an open source company and it's just a joke anyone would even use your systems now knowing what kind of legal recourse could be taken against them.  Your firm has the power to sue these people at any whim, again, the complete opposite rationale behind opensource companies.  

Get your shit together linagora
